[package]
name = "xkcd"
version = "0.1.0"
authors = ["AndyLnd <andy@wire.com>"]

[dependencies]
reqwest = "0.9.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2"

[dependencies.image]
version = "*"
features = ["png"]

[profile.release]
lto = true
opt-level = "s"